# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('height', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[(1, 'FAIR'), (2, 'DARK')], max_length=5, null=True)),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=50)),
                ('sub_caste', models.CharField(max_length=50)),
                ('martialStatus', models.CharField(choices=[(1, 'Single'), (2, 'Married'), (3, 'divorced')], default='single', max_length=25)),
                ('weight', models.CharField(max_length=15)),
                ('drink', models.CharField(max_length=15)),
                ('smoke', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateTimeField(verbose_name='Date of Birth/Time - format : YYYY-MM-DD HH:MM')),
                ('motherTongue', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=50)),
                ('blood_group', models.CharField(max_length=20)),
                ('placeOfBirth', models.CharField(max_length=50)),
                ('star', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=50)),
                ('education_detail', models.CharField(max_length=150)),
                ('occupation_detail', models.CharField(max_length=100)),
                ('annual_income', models.CharField(default='not specified', max_length=20)),
                ('current_location', models.CharField(max_length=30)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('no_of_sisters', models.IntegerField(default=0)),
                ('no_of_brothers', models.IntegerField(default=0)),
                ('partner_age_min', models.IntegerField(default=0)),
                ('partner_age_max', models.IntegerField(default=0)),
                ('partner_Martial_status', models.CharField(default=0, max_length=25)),
                ('partner_Height', models.CharField(max_length=25)),
                ('partner_Religion', models.CharField(max_length=25)),
                ('partner_Caste', models.CharField(max_length=25)),
                ('partner_Mother_Tongue', models.CharField(max_length=25)),
                ('partner_Education', models.CharField(max_length=25)),
            ],
        ),
    ]
