# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerss',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth/Time - format : YYYY-MM-DD HH:MM'),
        ),
    ]
