# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_re_enterpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='re_enterpassword',
        ),
    ]
