# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccount_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('education_detail', models.CharField(blank=True, max_length=150, null=True)),
                ('degree_certificate', models.FileField(null=True, upload_to='uploads/')),
                ('college_certificate', models.FileField(null=True, upload_to='uploads/')),
                ('school_certificate', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('present_residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('martialStatus', models.CharField(choices=[('1', 'Single'), ('2', 'Married'), ('3', 'divorced')], default='1', max_length=25)),
                ('DateOfBirth', models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth/Time - format : YYYY-MM-DD HH:MM')),
                ('mobile_number', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('alternativemobile_number', models.IntegerField(default=0)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_desigination', models.CharField(blank=True, max_length=20, null=True)),
                ('permanentAccount_number', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_joining', models.DateTimeField(blank=True, max_length=15, null=True)),
                ('passport_number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeewitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salarydetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_ctc', models.IntegerField(blank=True, default=0, null=True)),
                ('basic', models.IntegerField(blank=True, default=0, null=True)),
                ('other_allowances', models.IntegerField(blank=True, default=0, null=True)),
                ('pf_employee_contribution', models.IntegerField(blank=True, default=0, null=True)),
                ('esi', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
