# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('height', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[(1, 'FAIR'), (2, 'DARK')], max_length=5, null=True)),
            ],
        ),
    ]
