# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='caste',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='religion',
            field=models.CharField(default='po', max_length=20),
            preserve_default=False,
        ),
    ]
