# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181129_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='annual_income',
            field=models.CharField(default='not specified', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_group',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='current_location',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateTimeField(default='2018-12-12', verbose_name='Date of Birth/Time - format : YYYY-MM-DD HH:MM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='drink',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='education',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='education_detail',
            field=models.CharField(default='1', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='father_occupation',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='martialStatus',
            field=models.CharField(choices=[(1, 'Single'), (2, 'Married'), (3, 'divorced')], default='single', max_length=25),
        ),
        migrations.AddField(
            model_name='customer',
            name='medical_certificate',
            field=models.FileField(default='1', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='motherTongue',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mother_occupation',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_brothers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_sisters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation_detail',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_Caste',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_Education',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_Height',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_Martial_status',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_Mother_Tongue',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_Religion',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_age_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_age_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='placeOfBirth',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='smoke',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='star',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_caste',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
