# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20181220_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='color',
            field=models.CharField(blank=True, choices=[('1', 'FAIR'), ('2', 'DARK')], max_length=5, null=True),
        ),
    ]
