# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20181220_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
