# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20181220_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DateOfBirth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth/Time - format : YYYY-MM-DD HH:MM'),
        ),
    ]
