# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181118_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Mobile_number',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='education',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='re_enterpassword',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='relationship_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='work_details',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='gmail',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
